version: '3'
services:
  vault:
    tty: yes
    container_name: vault
    cap_add:
      - IPC_LOCK
    volumes:
      - "$INSTALLDIR/keys:/keys"
      - "$INSTALLDIR/certs:/certs"
    build: ./
    ports:
      - "8200:8200/tcp"