{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sapphire.serviceAccountName" . }}
  labels:
{{ include "sapphire.labels" . | indent 4 }}
{{- end -}}
